### ISSUE TITLE
class file for com.revenuecat.purchases.Purchases not found

### ISSUE THREAD

**Issue by Kieranshb** [andreidiaconu/flutter_revenuecat#1]
Hi, I have been using you revenue cat plugin and have just upgraded it today, after the Feb 18 (1.0.3) release. I have encountered an issue where I cannot compile the  flutter app on android due to a  class file for com.revenuecat.purchases.Purchases not found error

Here is the output that is created whenever I try to compile the app. 

`
D:\Workspace\project\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:58: error: cannot access Purchases
    RevenuecatPlugin.registerWith(registry.registrarFor("com.flutterplugin.revenuecat.RevenuecatPlugin"));
                    ^
  class file for com.revenuecat.purchases.Purchases not found
1 error
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:compileDevelopmentDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 16s
Gradle task assembleDevelopmentDebug failed with exit code 1
`

Any help that you can provide would be greatly appreciated! Thank you in advance for both your time and effort!

**Comment by cdharris** [comment]
Same issue here

**Comment by Kieranshb** [comment]
I was able to fix the problem by adding the following line to my \android\app\build.gradle file in the dependencies:

`implementation 'com.revenuecat.purchases:purchases:1.4.2'`

For example my dependencies look like this: 

```
dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.google.firebase:firebase-core:16.0.7'
    implementation 'androidx.appcompat:appcompat:1.0.0-alpha3'
    implementation 'com.revenuecat.purchases:purchases:1.4.2'
}
```

Hopefully this helps anyone still facing the issue!

**Comment by davidgalarza** [comment]
@Kieranshb  Thanks, a lot. It works perfectly now
